# Generated by Django 3.2 on 2021-06-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddata',
            name='author',
        ),
        migrations.RemoveField(
            model_name='adddata',
            name='content',
        ),
        migrations.RemoveField(
            model_name='adddata',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='adddata',
            name='slug',
        ),
    ]
